### ISSUE TITLE
Dark mode not working

### ISSUE THREAD

**Issue by Leoxur** [lukaslangrock/ShutdownTimerClassic#5]
Windows 10 2009, v.  1.2 of ShutdownTimerClassic

**Comment by lukaslangrock** [comment]
Thanks for your issue ✨
I am afraid there is currently no dark mode support but I will start working to implement it (could take some time tho, not quite sure how I would go about it).

**Comment by Leoxur** [comment]
![Immagine](https://user-images.githubusercontent.com/9626769/97428056-bcf34800-1915-11eb-95a9-a9a011dfe899.png)

**Comment by lukaslangrock** [comment]
No, sorry if this is a bit confusing. This option **just changes the icon** in the [tray menu](https://github.com/lukaslangrock/ShutdownTimerClassic/blob/master/Screenshots/TrayMenu.png) of your taskbar.

**Comment by Leoxur** [comment]
Ah ok, Sorry I misread the menu "tray" lol

**Comment by lukaslangrock** [comment]
It sadly looks like WinForms don't really fit well with themes, sorry there will be no dark mode support on this project :(

But I wanted to do another version of this anyways, hence the name. My original idea got somewhat stuck and is more of a concept than an anctual app (it kinda works tho, if u like tinkering feel free to [try it out](https://git.langrock.info/lukas-azure/ShutdownTimerUWP)). But since I switched to Fedora GNU/Linux recently I won't continue working with the UWP stuff like that concept.  But I'll make this into a cross-platform application once I figure out how to do that and there will definitely be dark mode support. I just don't know when.
